### ISSUE TITLE
Make up your mind between ending each line with `;` or not

### ISSUE THREAD

**Issue by killermonk** [aarondevon/snake-game#1]
I was browsing your JS and noticed that a bunch of lines end with `;`, but a bunch don't.

Pick one! No mixing!

:smile:

**Comment by aarondevon** [comment]
Good catch. I am not sure why I am missing so many `;`. I will get that cleaned up.

**Comment by aarondevon** [comment]
I am now implementing ESLint and the Airbnb style guide.
